### ISSUE TITLE
Task.leftShift(Closure) deprecation warnings with gradle 3.2

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-git-version#41]
On version 0.4.0, this stack trace appears during the configuration step (when running with `--info`)

```
[2016-11-21 09:59:41] The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
[2016-11-21 09:59:41] 	at org.gradle.api.internal.AbstractTask.leftShift(AbstractTask.java:505)
[2016-11-21 09:59:41] 	at org.gradle.api.Task$leftShift.call(Unknown Source)
[2016-11-21 09:59:41] 	at com.palantir.gradle.gitversion.GitVersionPlugin.apply(GitVersionPlugin.groovy:45)
[2016-11-21 09:59:41] 	at com.palantir.gradle.gitversion.GitVersionPlugin.apply(GitVersionPlugin.groovy)
[2016-11-21 09:59:41] 	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
[2016-11-21 09:59:41] 	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
[2016-11-21 09:59:41] 	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
[2016-11-21 09:59:41] 	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
[2016-11-21 09:59:41] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$5.run(DefaultPluginRequestApplicator.java:174)
[2016-11-21 09:59:41] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:212)
[2016-11-21 09:59:41] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:171)
[2016-11-21 09:59:41] 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:156)
[2016-11-21 09:59:41] 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
[2016-11-21 09:59:41] 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
[2016-11-21 09:59:41] 	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
[2016-11-21 09:59:41] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
[2016-11-21 09:59:41] 	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:573)
[2016-11-21 09:59:41] 	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
[2016-11-21 09:59:41] 	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
[2016-11-21 09:59:41] 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
[2016-11-21 09:59:41] 	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:162)
[2016-11-21 09:59:41] 	at org.gradle.internal.Factories$1.create(Factories.java:25)
[2016-11-21 09:59:41] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
[2016-11-21 09:59:41] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
[2016-11-21 09:59:41] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:159)
[2016-11-21 09:59:41] 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:36)
[2016-11-21 09:59:41] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:118)
[2016-11-21 09:59:41] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:112)
[2016-11-21 09:59:41] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
[2016-11-21 09:59:41] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
[2016-11-21 09:59:41] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
[2016-11-21 09:59:41] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:98)
[2016-11-21 09:59:41] 	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
[2016-11-21 09:59:41] 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
[2016-11-21 09:59:41] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
[2016-11-21 09:59:41] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
[2016-11-21 09:59:41] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
[2016-11-21 09:59:41] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
[2016-11-21 09:59:41] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
[2016-11-21 09:59:41] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
[2016-11-21 09:59:41] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
[2016-11-21 09:59:41] 	at org.gradle.util.Swapper.swap(Swapper.java:38)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
[2016-11-21 09:59:41] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
[2016-11-21 09:59:41] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
[2016-11-21 09:59:41] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
[2016-11-21 09:59:41] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-11-21 09:59:41] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-11-21 09:59:41] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by iamdanfox** [comment]
My mistake, it looks like this stacktrace doesn't appear when using com.palantir.git-version 0.5.2!
