### ISSUE TITLE
support git worktree structure

### ISSUE THREAD

**Issue by jboreiko** [palantir/gradle-git-version#65]
Currently the gradle-git-version plugin will return unspecified if you are using a directory that relies on [git worktrees](https://git-scm.com/docs/git-worktree).  

Unfortunately support for worktrees doesn't yet exist in JGit so I'm afraid we may have to wait a bit longer.  There was some movement on the issue recently - https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475 so maybe will have some luck.

**Comment by Andy-L** [comment]
What is the symptom?  I'm getting:
  "Cannot invoke method getObjectId() on null object" 
when I invoke `versionDetails()` in my `build.gradle`, and am wondering if it is the same issue.

**Comment by Andy-L** [comment]
and the stacktrace looks like:
```
Caused by: java.lang.NullPointerException: Cannot invoke method getObjectId() on null object
        at com.palantir.gradle.gitversion.GitVersionPlugin.memoizedMethodPriv$gitHashProject(GitVersionPlugin.groovy:86)
        at com.palantir.gradle.gitversion.GitVersionPlugin$_closure4.doCall(GitVersionPlugin.groovy)
        at com.palantir.gradle.gitversion.GitVersionPlugin.gitHash(GitVersionPlugin.groovy)
        at com.palantir.gradle.gitversion.GitVersionPlugin.memoizedMethodPriv$versionDetailsProject(GitVersionPlugin.groovy:53)
        at com.palantir.gradle.gitversion.GitVersionPlugin$_closure1.doCall(GitVersionPlugin.groovy)
        at com.palantir.gradle.gitversion.GitVersionPlugin.versionDetails(GitVersionPlugin.groovy)
        at com.palantir.gradle.gitversion.GitVersionPlugin$_apply_closure8.doCall(GitVersionPlugin.groovy:38)
        at com.palantir.gradle.gitversion.GitVersionPlugin$_apply_closure8.doCall(GitVersionPlugin.groovy)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:42)
        at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:134)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:83)
        at build_a79wtuvfihyiuvp95xqragq6t.run(/Users/andy/Workspace/javasrc2/ops/prometheus_config_syncer/build.gradle:34)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 93 more

```

**Comment by Andy-L** [comment]
And it worked with git worktrees on version `0.7.2` of the git-version plugin, but fails on `0.7.3`.

**Comment by jboreiko** [comment]
They symptom I saw was at the task level.  I.e. `./gradlew printVersion` returns `unspecified` which results from a failure to get a function Git object here - https://github.com/palantir/gradle-git-version/blob/42d3d043f063c35d3c59dce5e06bc768c283a437/src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy#L84 since the .git directory is actually just a file pointing to the worktree location.

**Comment by rocketraman** [comment]
Same issue here with 0.12.0-rc2 when running inside a git worktree (contains just a `.git` file instead of `.git` directory as noted by @jboreiko :

```
Caused by: java.lang.NullPointerException
  at com.palantir.gradle.gitversion.VersionDetails.getGitHashFull(VersionDetails.java:112)
  at com.palantir.gradle.gitversion.VersionDetails.getGitHash(VersionDetails.java:103)
  ... my code...
```

Note that even if the plugin can't actually understand a worktree, it should not have an NPE -- it should just return null or something to my code.

**Comment by kings129** [comment]
I also got NPE with a git worktree checkout, also think it would be better if versionDetails() just return null.

**Comment by aioobe** [comment]
Made an initial stab at it here https://github.com/palantir/gradle-git-version/pull/261

JGit still doesn't support worktrees, but my feeling is that native `git` will be available most of the times when worktrees are in use, so a native `git` based implementation should hopefully cover most cases.

**Comment by ilka-schulz** [comment]
I think worktree support should be similar to submodule support (https://github.com/palantir/gradle-git-version/issues/111) because in both cases we need to read the `.git` file to find out the git directory. I have successfully tested this workaround (https://github.com/palantir/gradle-git-version/pull/500) for submodules.

The main idea in pseudo code is:
```text
if directory is a submodule (e.g. `.git` file is an ordinary file):
    RepositoryBuilder builder = new RepositoryBuilder();
    builder.setWorkTree( directory's parent );
    builder.setGitDir( path read from `.git` file );
    Repository subRepo = builder.build();
    git = Git.wrap(subRepo);
else:
    git = Git.wrap(new FileRepository( directory )); // JGit::wrap works as expected for superrepos
```

**Comment by lapo-luchini** [comment]
I upgraded to `3.0.0` which (as far as I understood) no longer uses `jgit`, but I still get this when using a git worktree:

```
% cd branch-worktree
% git describe --tags
1.3.0-12-gbbc07f3
% git describe --all
heads/coll_20230518
% gradle printVersion
> Task :printVersion
unspecified
```

**Comment by lapo-luchini** [comment]
Sorry, that was a problem on my part: Gradle was using a different `git` exe than the commandline was, I can confirm it is working properly in a worktree!

**Comment by ash211** [comment]
I'm seeing a similar issue, where I have two `git` exe on my PATH:

```
$ which -a git
/opt/homebrew/bin/git
/usr/bin/git
```

But both `git` binaries return an expected tag version:
```
$ git describe --tags --always --first-parent --abbrev=7
0.0.2
$ /usr/bin/git describe --tags --always --first-parent --abbrev=7
0.0.2
$ /opt/homebrew/bin/git describe --tags --always --first-parent --abbrev=7
0.0.2
$
```

When I run `./gradlew printVersion` it  returns `unspecified` though :/

Adding this to the end of my `build.gradle` shows that the `versionDetails()` is populated though:

```gradle
def details = versionDetails()
println("details.lastTag: " + details.lastTag)
println("details.commitDistance: " + details.commitDistance)
println("details.gitHash: " + details.gitHash)
println("details.gitHashFull: " + details.gitHashFull) // full 40-character Git commit hash
println("details.branchName: " + details.branchName) // is null if the repository in detached HEAD mode
println("details.isCleanTag: " + details.isCleanTag)
println("gitVersion(): " + gitVersion())
```

```
details.lastTag: 0.0.2
details.commitDistance: 0
details.gitHash: 150afb9013
details.gitHashFull: 150afb9013971138ff5098a948ac62b64fa24783
details.branchName: master
details.isCleanTag: false
gitVersion(): 0.0.2.dirty
```

Very unsure why printVersion gives

```
> Task :printVersion
unspecified
```

I'm not using git worktree at all (that I know of), so maybe this is unrelated.

**Comment by ash211** [comment]
Conclusion for my issue above: `printVersion` prints the project's version, not the version that gradle-git-version returned.  To set the former to the latter, add

```
version gitVersion()
```

With that, `./gradlew printVersion` does what I expect on this repo
